# Generated by Django 5.0.3 on 2024-03-21 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
            ],
            options={
                "ordering": ["nome", "estado"],
            },
        ),
        migrations.CreateModel(
            name="Estudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "matricula",
                    models.CharField(max_length=255, verbose_name="Matrícula"),
                ),
                ("data_nascimento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estagio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.TextField(max_length=255)),
                ("data_inicio", models.DateField()),
                ("data_termino", models.DateField(blank=True, null=True)),
                ("data_protocolo", models.DateTimeField(auto_now_add=True)),
                (
                    "protocolado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estagios",
                        to="cadastros.estudante",
                    ),
                ),
            ],
        ),
    ]
